behaviors:
  SliderBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 8912
      buffer_size: 65536
      learning_rate: 2.5e-5
      beta: 0.0001
      epsilon: 0.05
      lambd: 0.99
      num_epoch: 15
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 2000000
    time_horizon: 2048
    summary_freq: 500
