behaviors:
  SliderBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 3000
      learning_rate: 6.0e-4
      beta: 5.0e-3
      epsilon: 0.6
      lambd: 0.99
      num_epoch: 15
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 20000
    time_horizon: 64
    summary_freq: 10000