behaviors:
  SliderBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 5.0e-5
      beta: 0.003
      epsilon: 0.05
      lambd: 0.99
      num_epoch: 8
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.2
    max_steps: 200000
    time_horizon: 64
    summary_freq: 1000
