behaviors:
  SliderBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10240
      buffer_size: 65536
      learning_rate: 2.5e-5
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 15
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 2048
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 2.0
    max_steps: 2000000
    time_horizon: 2048
    summary_freq: 500
